//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApi.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRequest", Namespace="http://schemas.datacontract.org/2004/07/DataContract")]
    [System.SerializableAttribute()]
    public partial class UserRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarId {
            get {
                return this.CarIdField;
            }
            set {
                if ((this.CarIdField.Equals(value) != true)) {
                    this.CarIdField = value;
                    this.RaisePropertyChanged("CarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CreateUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestApi.UserServiceReference.UserRequest inputUserRequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestApi.UserServiceReference.UserRequest inputUserRequest {
            get {
                return this.inputUserRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.inputUserRequestField, value) != true)) {
                    this.inputUserRequestField = value;
                    this.RaisePropertyChanged("inputUserRequest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserById", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetUserById : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int inputUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int inputUserId {
            get {
                return this.inputUserIdField;
            }
            set {
                if ((this.inputUserIdField.Equals(value) != true)) {
                    this.inputUserIdField = value;
                    this.RaisePropertyChanged("inputUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IService")]
    public interface IService {
        
        // CODEGEN: Generating message contract since the operation CreateUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUser", ReplyAction="http://tempuri.org/IService/CreateUserResponse")]
        RestApi.UserServiceReference.CreateUserResponse CreateUser(RestApi.UserServiceReference.CreateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUser", ReplyAction="http://tempuri.org/IService/CreateUserResponse")]
        System.Threading.Tasks.Task<RestApi.UserServiceReference.CreateUserResponse> CreateUserAsync(RestApi.UserServiceReference.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since the operation DeleteUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteUser", ReplyAction="http://tempuri.org/IService/DeleteUserResponse")]
        RestApi.UserServiceReference.DeleteUserResponse DeleteUser(RestApi.UserServiceReference.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteUser", ReplyAction="http://tempuri.org/IService/DeleteUserResponse")]
        System.Threading.Tasks.Task<RestApi.UserServiceReference.DeleteUserResponse> DeleteUserAsync(RestApi.UserServiceReference.DeleteUserRequest request);
        
        // CODEGEN: Generating message contract since the operation GetAllUsers is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        RestApi.UserServiceReference.GetAllUsersResponse GetAllUsers(RestApi.UserServiceReference.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<RestApi.UserServiceReference.GetAllUsersResponse> GetAllUsersAsync(RestApi.UserServiceReference.GetAllUsersRequest request);
        
        // CODEGEN: Generating message contract since the operation GetUserById is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserById", ReplyAction="http://tempuri.org/IService/GetUserByIdResponse")]
        RestApi.UserServiceReference.GetUserByIdResponse GetUserById(RestApi.UserServiceReference.GetUserByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserById", ReplyAction="http://tempuri.org/IService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<RestApi.UserServiceReference.GetUserByIdResponse> GetUserByIdAsync(RestApi.UserServiceReference.GetUserByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RestApi.UserServiceReference.CreateUser CreateUser;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(RestApi.UserServiceReference.CreateUser CreateUser) {
            this.CreateUser = CreateUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<int> @int;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(System.Nullable<int> @int) {
            this.@int = @int;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int inputUserId;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(int inputUserId) {
            this.inputUserId = inputUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        public DeleteUserResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        public GetAllUsersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/DataContract", Order=0)]
        public RestApi.UserServiceReference.UserRequest[] ArrayOfUserRequest;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(RestApi.UserServiceReference.UserRequest[] ArrayOfUserRequest) {
            this.ArrayOfUserRequest = ArrayOfUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RestApi.UserServiceReference.GetUserById GetUserById;
        
        public GetUserByIdRequest() {
        }
        
        public GetUserByIdRequest(RestApi.UserServiceReference.GetUserById GetUserById) {
            this.GetUserById = GetUserById;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/DataContract", Order=0)]
        public RestApi.UserServiceReference.UserRequest UserRequest;
        
        public GetUserByIdResponse() {
        }
        
        public GetUserByIdResponse(RestApi.UserServiceReference.UserRequest UserRequest) {
            this.UserRequest = UserRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : RestApi.UserServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<RestApi.UserServiceReference.IService>, RestApi.UserServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestApi.UserServiceReference.CreateUserResponse RestApi.UserServiceReference.IService.CreateUser(RestApi.UserServiceReference.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public System.Nullable<int> CreateUser(RestApi.UserServiceReference.CreateUser CreateUser1) {
            RestApi.UserServiceReference.CreateUserRequest inValue = new RestApi.UserServiceReference.CreateUserRequest();
            inValue.CreateUser = CreateUser1;
            RestApi.UserServiceReference.CreateUserResponse retVal = ((RestApi.UserServiceReference.IService)(this)).CreateUser(inValue);
            return retVal.@int;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestApi.UserServiceReference.CreateUserResponse> RestApi.UserServiceReference.IService.CreateUserAsync(RestApi.UserServiceReference.CreateUserRequest request) {
            return base.Channel.CreateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestApi.UserServiceReference.CreateUserResponse> CreateUserAsync(RestApi.UserServiceReference.CreateUser CreateUser) {
            RestApi.UserServiceReference.CreateUserRequest inValue = new RestApi.UserServiceReference.CreateUserRequest();
            inValue.CreateUser = CreateUser;
            return ((RestApi.UserServiceReference.IService)(this)).CreateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestApi.UserServiceReference.DeleteUserResponse RestApi.UserServiceReference.IService.DeleteUser(RestApi.UserServiceReference.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public void DeleteUser(int inputUserId) {
            RestApi.UserServiceReference.DeleteUserRequest inValue = new RestApi.UserServiceReference.DeleteUserRequest();
            inValue.inputUserId = inputUserId;
            RestApi.UserServiceReference.DeleteUserResponse retVal = ((RestApi.UserServiceReference.IService)(this)).DeleteUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestApi.UserServiceReference.DeleteUserResponse> RestApi.UserServiceReference.IService.DeleteUserAsync(RestApi.UserServiceReference.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestApi.UserServiceReference.DeleteUserResponse> DeleteUserAsync(int inputUserId) {
            RestApi.UserServiceReference.DeleteUserRequest inValue = new RestApi.UserServiceReference.DeleteUserRequest();
            inValue.inputUserId = inputUserId;
            return ((RestApi.UserServiceReference.IService)(this)).DeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestApi.UserServiceReference.GetAllUsersResponse RestApi.UserServiceReference.IService.GetAllUsers(RestApi.UserServiceReference.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public RestApi.UserServiceReference.UserRequest[] GetAllUsers() {
            RestApi.UserServiceReference.GetAllUsersRequest inValue = new RestApi.UserServiceReference.GetAllUsersRequest();
            RestApi.UserServiceReference.GetAllUsersResponse retVal = ((RestApi.UserServiceReference.IService)(this)).GetAllUsers(inValue);
            return retVal.ArrayOfUserRequest;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestApi.UserServiceReference.GetAllUsersResponse> RestApi.UserServiceReference.IService.GetAllUsersAsync(RestApi.UserServiceReference.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestApi.UserServiceReference.GetAllUsersResponse> GetAllUsersAsync() {
            RestApi.UserServiceReference.GetAllUsersRequest inValue = new RestApi.UserServiceReference.GetAllUsersRequest();
            return ((RestApi.UserServiceReference.IService)(this)).GetAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestApi.UserServiceReference.GetUserByIdResponse RestApi.UserServiceReference.IService.GetUserById(RestApi.UserServiceReference.GetUserByIdRequest request) {
            return base.Channel.GetUserById(request);
        }
        
        public RestApi.UserServiceReference.UserRequest GetUserById(RestApi.UserServiceReference.GetUserById GetUserById1) {
            RestApi.UserServiceReference.GetUserByIdRequest inValue = new RestApi.UserServiceReference.GetUserByIdRequest();
            inValue.GetUserById = GetUserById1;
            RestApi.UserServiceReference.GetUserByIdResponse retVal = ((RestApi.UserServiceReference.IService)(this)).GetUserById(inValue);
            return retVal.UserRequest;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestApi.UserServiceReference.GetUserByIdResponse> RestApi.UserServiceReference.IService.GetUserByIdAsync(RestApi.UserServiceReference.GetUserByIdRequest request) {
            return base.Channel.GetUserByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestApi.UserServiceReference.GetUserByIdResponse> GetUserByIdAsync(RestApi.UserServiceReference.GetUserById GetUserById) {
            RestApi.UserServiceReference.GetUserByIdRequest inValue = new RestApi.UserServiceReference.GetUserByIdRequest();
            inValue.GetUserById = GetUserById;
            return ((RestApi.UserServiceReference.IService)(this)).GetUserByIdAsync(inValue);
        }
    }
}
