//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.eDrvenija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class dokumenti
    {
        [Key]
        [ScaffoldColumn(false)]
        public int idDokumenta { get; set; }

        [DisplayName("Dokument")]
        [Required(ErrorMessage="Potrebno je unijeti dokument")]
        public byte[] dokument { get; set; }

        [DisplayName("Broj preuzimanja")]
        [ReadOnly(true)]
        public Nullable<int> brojPreuzimanja { get; set; }

        [DisplayName("Odaberite oglas")]
        [Required(ErrorMessage="Potrebno je odabrati oglas")]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public int idOglasa { get; set; }
    
        public virtual oglasi oglasi { get; set; }
    }
}
