//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.eDrvenija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using Resursi;
    
    public partial class kategorije
    {
        public kategorije()
        {
            this.korisnicikategorije = new HashSet<korisnicikategorije>();
            this.oglasi = new HashSet<oglasi>();
        }

        [Key]
        [ScaffoldColumn(false)]
        public int idKategorije { get; set; }

        [Display(Name = "Kategorija", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "KategorijaReq", ErrorMessageResourceType = typeof(Resursi))]
        [MaxLength(45, ErrorMessageResourceName = "KategorijaLen", ErrorMessageResourceType = typeof(Resursi))]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string nazivKategorije { get; set; }
    
        public virtual ICollection<korisnicikategorije> korisnicikategorije { get; set; }
        public virtual ICollection<oglasi> oglasi { get; set; }
    }
}
