//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.eDrvenija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using Resursi;
    
    public partial class korisnici
    {
        public korisnici()
        {
            this.komentari = new HashSet<komentari>();
            this.korisnicikategorije = new HashSet<korisnicikategorije>();
            this.logovi = new HashSet<logovi>();
            this.oglasi = new HashSet<oglasi>();
            this.poruke = new HashSet<poruke>();
            this.poruke1 = new HashSet<poruke>();
            this.statusi = new HashSet<statusi>();
            this.transakcije = new HashSet<transakcije>();
        }
    
        [Key]
        [ScaffoldColumn(false)]
        public int idKorisnika { get; set; }
        
        [Display(Name="Ime", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "ImeReq", ErrorMessageResourceType = typeof(Resursi))]
        [MaxLength(45, ErrorMessageResourceName = "ImeLen", ErrorMessageResourceType = typeof(Resursi))]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string imeKorisnika { get; set; }

        [Display(Name = "Prezime", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "PrezimeReq", ErrorMessageResourceType = typeof(Resursi))]
        [MaxLength(45, ErrorMessageResourceName = "PrezimeLen", ErrorMessageResourceType = typeof(Resursi))]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string prezimeKorisnika { get; set; }

        [Display(Name = "Email", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "EmailReq", ErrorMessageResourceType = typeof(Resursi))]
        [MaxLength(45, ErrorMessageResourceName = "EmailLen", ErrorMessageResourceType = typeof(Resursi))]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessageResourceName = "EmailIs", ErrorMessageResourceType = typeof(Resursi))]
        public string eMailKorisnika { get; set; }

        [Display(Name = "BrojTelefona", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "BrojTelefonaReq", ErrorMessageResourceType = typeof(Resursi))]
        [MaxLength(45, ErrorMessageResourceName = "BrojTelefonaLen", ErrorMessageResourceType = typeof(Resursi))]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [DataType(DataType.PhoneNumber)]
        [Phone(ErrorMessageResourceName = "BrojTelefonaIs", ErrorMessageResourceType = typeof(Resursi))]
        public string brojTelefonaKorisnika { get; set; }

        [Display(Name = "Avatar", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "AvatarReq", ErrorMessageResourceType = typeof(Resursi))]
        public byte[] avatarKorisnika { get; set; }

        [Display(Name = "Ocjena", ResourceType = typeof(Resursi))]
        [Range(1.00, 5.00, ErrorMessageResourceName = "OcjenaRange", ErrorMessageResourceType = typeof(Resursi))]
        public Nullable<double> ocjena { get; set; }

        [Display(Name = "KorisnikAktivanOd", ResourceType = typeof(Resursi))]
        public Nullable<System.DateTime> korisnikAktivanOd { get; set; }

        [Display(Name = "KorisnickoIme", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "KorisnickoImeReq", ErrorMessageResourceType = typeof(Resursi))]
        [MaxLength(45, ErrorMessageResourceName = "KorisnickoImeLen", ErrorMessageResourceType = typeof(Resursi))]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string korisnickoImeKorisnika { get; set; }

        [Display(Name = "Loznika", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "LoznikaReq", ErrorMessageResourceType = typeof(Resursi))]
        [MaxLength(45, ErrorMessageResourceName = "LoznikaLen", ErrorMessageResourceType = typeof(Resursi))]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [DataType(DataType.Password)]
        [PasswordPropertyText]
        public string lozinkaKorisnika { get; set; }

        [ScaffoldColumn(false)]
        public Nullable<bool> aktivan { get; set; }

        [Display(Name = "TipKorisnika", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "TipKorisnikaReq", ErrorMessageResourceType = typeof(Resursi))]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public int idTipaKorisnika { get; set; }
    
        public virtual ICollection<komentari> komentari { get; set; }
        public virtual tipovikorisnika tipovikorisnika { get; set; }
        public virtual ICollection<korisnicikategorije> korisnicikategorije { get; set; }
        public virtual ICollection<logovi> logovi { get; set; }
        public virtual ICollection<oglasi> oglasi { get; set; }
        public virtual ICollection<poruke> poruke { get; set; }
        public virtual ICollection<poruke> poruke1 { get; set; }
        public virtual ICollection<statusi> statusi { get; set; }
        public virtual ICollection<transakcije> transakcije { get; set; }
    }
}
