//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.eDrvenija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnici
    {
        public korisnici()
        {
            this.komentari = new HashSet<komentari>();
            this.korisnicikategorije = new HashSet<korisnicikategorije>();
            this.logovi = new HashSet<logovi>();
            this.ocjene = new HashSet<ocjene>();
            this.oglasi = new HashSet<oglasi>();
            this.poruke = new HashSet<poruke>();
            this.poruke1 = new HashSet<poruke>();
            this.statusi = new HashSet<statusi>();
            this.transakcije = new HashSet<transakcije>();
            this.upiti = new HashSet<upiti>();
        }
    
        public int idKorisnika { get; set; }
        public string imeKorisnika { get; set; }
        public string prezimeKorisnika { get; set; }
        public string eMailKorisnika { get; set; }
        public string brojTelefonaKorisnika { get; set; }
        public byte[] avatarKorisnika { get; set; }
        public Nullable<double> ocjena { get; set; }
        public Nullable<System.DateTime> korisnikAktivanOd { get; set; }
        public string korisnickoImeKorisnika { get; set; }
        public string lozinkaKorisnika { get; set; }
        public Nullable<bool> aktivan { get; set; }
        public int idTipaKorisnika { get; set; }
    
        public virtual ICollection<komentari> komentari { get; set; }
        public virtual tipovikorisnika tipovikorisnika { get; set; }
        public virtual ICollection<korisnicikategorije> korisnicikategorije { get; set; }
        public virtual ICollection<logovi> logovi { get; set; }
        public virtual ICollection<ocjene> ocjene { get; set; }
        public virtual ICollection<oglasi> oglasi { get; set; }
        public virtual ICollection<poruke> poruke { get; set; }
        public virtual ICollection<poruke> poruke1 { get; set; }
        public virtual ICollection<statusi> statusi { get; set; }
        public virtual ICollection<transakcije> transakcije { get; set; }
        public virtual ICollection<upiti> upiti { get; set; }
    }
}
