//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.eDrvenija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class korisnicikategorije
    {
        [Key]
        public int idKorisnikaKategorije { get; set; }
    
        public virtual kategorije kategorije { get; set; }
        public virtual korisnici korisnici { get; set; }
    }
}
