//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.eDrvenija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class oglasi
    {
        public oglasi()
        {
            this.dokumenti = new HashSet<dokumenti>();
            this.komentari = new HashSet<komentari>();
            this.transakcije = new HashSet<transakcije>();
        }
    
        [Key]
        public int idOglasa { get; set; }
        public string nazivOglasa { get; set; }
        public Nullable<System.DateTime> datumObjaveOglasa { get; set; }
        public string opisOglasa { get; set; }
        public Nullable<double> cijena { get; set; }
        public Nullable<int> brojPregledaOglasa { get; set; }
        public Nullable<bool> zavrsenaTransakcija { get; set; }
        public Nullable<bool> aktivan { get; set; }
        public int idTipaOglasa { get; set; }
        public int idKategorije { get; set; }
        public int idKorisnika { get; set; }
    
        public virtual ICollection<dokumenti> dokumenti { get; set; }
        public virtual kategorije kategorije { get; set; }
        public virtual ICollection<komentari> komentari { get; set; }
        public virtual korisnici korisnici { get; set; }
        public virtual tipovioglasa tipovioglasa { get; set; }
        public virtual ICollection<transakcije> transakcije { get; set; }
    }
}
