//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.eDrvenija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Resursi;
    
    public partial class poruke
    {
        [Key]
        [ScaffoldColumn(false)]
        public int idPoruke { get; set; }

        [Display(Name = "NaslovPoruke", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "NaslovPorukeReq", ErrorMessageResourceType = typeof(Resursi))]
        [StringLength(45, ErrorMessageResourceName = "NaslovPorukeLen", ErrorMessageResourceType = typeof(Resursi))]
        public string naslovPoruke { get; set; }

        [Display(Name = "TekstPoruke", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "TekstPorukeReq", ErrorMessageResourceType = typeof(Resursi))]
        [StringLength(1000, ErrorMessageResourceName = "TekstPorukeLen", ErrorMessageResourceType = typeof(Resursi))]
        public string tekstPoruke { get; set; }

        [ScaffoldColumn(false)]
        public Nullable<bool> aktivan { get; set; }

        [Display(Name = "Posiljaoc", ResourceType = typeof(Resursi))]
        public int idKorisnikaPosiljaoca { get; set; }

        [Display(Name = "Primaoc", ResourceType = typeof(Resursi))]
        public int idKorisnikaPrimaoca { get; set; }
    
        public virtual korisnici korisnici { get; set; }
        public virtual korisnici korisnici1 { get; set; }
    }
}
