//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.eDrvenija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class poruke
    {
        public int idPoruke { get; set; }
        public string naslovPoruke { get; set; }
        public string tekstPoruke { get; set; }
        public Nullable<bool> aktivan { get; set; }
        public int idKorisnikaPosiljaoca { get; set; }
        public int idKorisnikaPrimaoca { get; set; }
    
        public virtual korisnici korisnici { get; set; }
        public virtual korisnici korisnici1 { get; set; }
    }
}
