//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.eDrvenija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Resursi;
    
    public partial class tipovioglasa
    {
        public tipovioglasa()
        {
            this.oglasi = new HashSet<oglasi>();
        }
    
        [Key]
        [ScaffoldColumn(false)]
        public int idTipaOglasa { get; set; }

        [Display(Name = "NazivTipaOglasa", ResourceType = typeof(Resursi))]
        [Required(ErrorMessageResourceName = "NazivTipaOglasaReq", ErrorMessageResourceType = typeof(Resursi))]
        [StringLength(45, ErrorMessageResourceName = "NazivTipaOglasaLen", ErrorMessageResourceType = typeof(Resursi))]
        public string nazivTipaOglasa { get; set; }
    
        public virtual ICollection<oglasi> oglasi { get; set; }
    }
}
