//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.eDrvenija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    
    public partial class tipovikorisnika
    {
        public tipovikorisnika()
        {
            this.korisnici = new HashSet<korisnici>();
        }
    
        [ScaffoldColumn(false)]
        public int idTipaKorisnika { get; set; }
        [DisplayName("Tip korisnika")]
        [Required(ErrorMessage="Potrebno je unijeti naziv tipa korisnika i ne smije biti duži od 45 znakova")]
        [DisplayFormat(ConvertEmptyStringToNull=false)]
        public string nazivTipaKorisnika { get; set; }
    
        public virtual ICollection<korisnici> korisnici { get; set; }
    }
}
