//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.eDrvenija.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tipovioglasa
    {
        public tipovioglasa()
        {
            this.oglasi = new HashSet<oglasi>();
        }
    
        [Key]
        [ScaffoldColumn(false)]
        public int idTipaOglasa { get; set; }

        [DisplayName("Tip oglasa")]
        [Required(ErrorMessage = "Potrebno je unijeti naziv tipa oglasa i ne smije biti duži od 45 znakova")]
        [MaxLength(45, ErrorMessage="Maksimalna dužina je 45 znakova")]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string nazivTipaOglasa { get; set; }
    
        public virtual ICollection<oglasi> oglasi { get; set; }
    }
}
