//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDrvenija.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class statusi
    {
        public int idStatusa { get; set; }
        public Nullable<int> brojProdaja { get; set; }
        public Nullable<int> brojKupovina { get; set; }
        public Nullable<System.DateTime> korisnikAktivanOd { get; set; }
        public int idKorisnika { get; set; }
    
        public virtual korisnici korisnici { get; set; }
    }
}
