//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resursi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resursi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resursi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resursi.Resursi", typeof(Resursi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        public static string Detalji {
            get {
                return ResourceManager.GetString("Detalji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna stranica.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije.
        /// </summary>
        public static string Informacije {
            get {
                return ResourceManager.GetString("Informacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite jezik.
        /// </summary>
        public static string IzaberiteJezik {
            get {
                return ResourceManager.GetString("IzaberiteJezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktiraj nas.
        /// </summary>
        public static string KontaktirajNas {
            get {
                return ResourceManager.GetString("KontaktirajNas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnici.
        /// </summary>
        public static string Korisnici {
            get {
                return ResourceManager.GetString("Korisnici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj.
        /// </summary>
        public static string Kreiraj {
            get {
                return ResourceManager.GetString("Kreiraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj novi.
        /// </summary>
        public static string KreirajNovi {
            get {
                return ResourceManager.GetString("KreirajNovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkovi.
        /// </summary>
        public static string Linkovi {
            get {
                return ResourceManager.GetString("Linkovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad na početnu.
        /// </summary>
        public static string NazadNaPocetnu {
            get {
                return ResourceManager.GetString("NazadNaPocetnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv tipa korisnika.
        /// </summary>
        public static string NazivTipaKorisnika {
            get {
                return ResourceManager.GetString("NazivTipaKorisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string NazivTipaKorisnikaLen {
            get {
                return ResourceManager.GetString("NazivTipaKorisnikaLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti naziv tipa korisnika.
        /// </summary>
        public static string NazivTipaKorisnikaReq {
            get {
                return ResourceManager.GetString("NazivTipaKorisnikaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string Obrisi {
            get {
                return ResourceManager.GetString("Obrisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da ovo želite obrisati?.
        /// </summary>
        public static string ObrisiPitanje {
            get {
                return ResourceManager.GetString("ObrisiPitanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oglasi.
        /// </summary>
        public static string Oglasi {
            get {
                return ResourceManager.GetString("Oglasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nama.
        /// </summary>
        public static string Onama {
            get {
                return ResourceManager.GetString("Onama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string Sacuvaj {
            get {
                return ResourceManager.GetString("Sacuvaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipovi korisnika.
        /// </summary>
        public static string TipoviKorisnika {
            get {
                return ResourceManager.GetString("TipoviKorisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        public static string Uredi {
            get {
                return ResourceManager.GetString("Uredi", resourceCulture);
            }
        }
    }
}
