//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resursi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resursi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resursi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resursi.Resursi", typeof(Resursi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcije.
        /// </summary>
        public static string Akcije {
            get {
                return ResourceManager.GetString("Akcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivni/Inaktivni korisnici.
        /// </summary>
        public static string AktivniInaktivniKorisnici {
            get {
                return ResourceManager.GetString("AktivniInaktivniKorisnici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je učitati avatar.
        /// </summary>
        public static string AvatarReq {
            get {
                return ResourceManager.GetString("AvatarReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj.
        /// </summary>
        public static string Broj {
            get {
                return ResourceManager.GetString("Broj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj kupovina.
        /// </summary>
        public static string BrojKupovina {
            get {
                return ResourceManager.GetString("BrojKupovina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj novih korisnika u zadnjih.
        /// </summary>
        public static string BrojNovihKorisnikaUZadnjih {
            get {
                return ResourceManager.GetString("BrojNovihKorisnikaUZadnjih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj pregleda.
        /// </summary>
        public static string BrojPregledaOglasa {
            get {
                return ResourceManager.GetString("BrojPregledaOglasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj preuzimanja.
        /// </summary>
        public static string BrojPreuzimanja {
            get {
                return ResourceManager.GetString("BrojPreuzimanja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj prodaja.
        /// </summary>
        public static string BrojProdaja {
            get {
                return ResourceManager.GetString("BrojProdaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        public static string BrojTelefona {
            get {
                return ResourceManager.GetString("BrojTelefona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon nije validan.
        /// </summary>
        public static string BrojTelefonaIs {
            get {
                return ResourceManager.GetString("BrojTelefonaIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string BrojTelefonaLen {
            get {
                return ResourceManager.GetString("BrojTelefonaLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti broj telefona.
        /// </summary>
        public static string BrojTelefonaReq {
            get {
                return ResourceManager.GetString("BrojTelefonaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena.
        /// </summary>
        public static string Cijena {
            get {
                return ResourceManager.GetString("Cijena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti cijenu.
        /// </summary>
        public static string CijenaReq {
            get {
                return ResourceManager.GetString("CijenaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum objave.
        /// </summary>
        public static string DatumObjaveOglasa {
            get {
                return ResourceManager.GetString("DatumObjaveOglasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum transakcije.
        /// </summary>
        public static string DatumTransakcije {
            get {
                return ResourceManager.GetString("DatumTransakcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti datum transakcije.
        /// </summary>
        public static string DatumTransakcijeReq {
            get {
                return ResourceManager.GetString("DatumTransakcijeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        public static string Detalji {
            get {
                return ResourceManager.GetString("Detalji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli.
        /// </summary>
        public static string Dobrodosli {
            get {
                return ResourceManager.GetString("Dobrodosli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument.
        /// </summary>
        public static string Dokument {
            get {
                return ResourceManager.GetString("Dokument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenti.
        /// </summary>
        public static string Dokumenti {
            get {
                return ResourceManager.GetString("Dokumenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je učitati dokument.
        /// </summary>
        public static string DokumentReq {
            get {
                return ResourceManager.GetString("DokumentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugi.
        /// </summary>
        public static string Drugi {
            get {
                return ResourceManager.GetString("Drugi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email nije validan.
        /// </summary>
        public static string EmailIs {
            get {
                return ResourceManager.GetString("EmailIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string EmailLen {
            get {
                return ResourceManager.GetString("EmailLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti email.
        /// </summary>
        public static string EmailReq {
            get {
                return ResourceManager.GetString("EmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 365 dana.
        /// </summary>
        public static string Godinadana {
            get {
                return ResourceManager.GetString("Godinadana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string ImeLen {
            get {
                return ResourceManager.GetString("ImeLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti ime.
        /// </summary>
        public static string ImeReq {
            get {
                return ResourceManager.GetString("ImeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna stranica.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije.
        /// </summary>
        public static string Informacije {
            get {
                return ResourceManager.GetString("Informacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite jezik.
        /// </summary>
        public static string IzaberiteJezik {
            get {
                return ResourceManager.GetString("IzaberiteJezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija.
        /// </summary>
        public static string Kategorija {
            get {
                return ResourceManager.GetString("Kategorija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string KategorijaLen {
            get {
                return ResourceManager.GetString("KategorijaLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti kategoriju.
        /// </summary>
        public static string KategorijaReq {
            get {
                return ResourceManager.GetString("KategorijaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorije.
        /// </summary>
        public static string Kategorije {
            get {
                return ResourceManager.GetString("Kategorije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klikni me.
        /// </summary>
        public static string KlikniMe {
            get {
                return ResourceManager.GetString("KlikniMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentari.
        /// </summary>
        public static string Komentari {
            get {
                return ResourceManager.GetString("Komentari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktiraj nas.
        /// </summary>
        public static string KontaktirajNas {
            get {
                return ResourceManager.GetString("KontaktirajNas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnici.
        /// </summary>
        public static string Korisnici {
            get {
                return ResourceManager.GetString("Korisnici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnici po ocjeni.
        /// </summary>
        public static string KorisniciPoOcjeni {
            get {
                return ResourceManager.GetString("KorisniciPoOcjeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime.
        /// </summary>
        public static string KorisnickoIme {
            get {
                return ResourceManager.GetString("KorisnickoIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string KorisnickoImeLen {
            get {
                return ResourceManager.GetString("KorisnickoImeLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti korisnicko ime.
        /// </summary>
        public static string KorisnickoImeReq {
            get {
                return ResourceManager.GetString("KorisnickoImeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik.
        /// </summary>
        public static string Korisnik {
            get {
                return ResourceManager.GetString("Korisnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik aktivan od.
        /// </summary>
        public static string KorisnikAktivanOd {
            get {
                return ResourceManager.GetString("KorisnikAktivanOd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je odabrati korisnika.
        /// </summary>
        public static string KorisnikReq {
            get {
                return ResourceManager.GetString("KorisnikReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj.
        /// </summary>
        public static string Kreiraj {
            get {
                return ResourceManager.GetString("Kreiraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj novi.
        /// </summary>
        public static string KreirajNovi {
            get {
                return ResourceManager.GetString("KreirajNovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkovi.
        /// </summary>
        public static string Linkovi {
            get {
                return ResourceManager.GetString("Linkovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Lozinka {
            get {
                return ResourceManager.GetString("Lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string LozinkaLen {
            get {
                return ResourceManager.GetString("LozinkaLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti lozinku.
        /// </summary>
        public static string LozinkaReq {
            get {
                return ResourceManager.GetString("LozinkaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 dana.
        /// </summary>
        public static string Mjesecdana {
            get {
                return ResourceManager.GetString("Mjesecdana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mjesto.
        /// </summary>
        public static string Mjesto {
            get {
                return ResourceManager.GetString("Mjesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najveca tri broja kupovina i prodaja.
        /// </summary>
        public static string NajvecaTriBrojaKupovinaProdaja {
            get {
                return ResourceManager.GetString("NajvecaTriBrojaKupovinaProdaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov poruke.
        /// </summary>
        public static string NaslovPoruke {
            get {
                return ResourceManager.GetString("NaslovPoruke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string NaslovPorukeLen {
            get {
                return ResourceManager.GetString("NaslovPorukeLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti naslov poruke.
        /// </summary>
        public static string NaslovPorukeReq {
            get {
                return ResourceManager.GetString("NaslovPorukeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad na početnu.
        /// </summary>
        public static string NazadNaPocetnu {
            get {
                return ResourceManager.GetString("NazadNaPocetnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv oglasa.
        /// </summary>
        public static string NazivOglasa {
            get {
                return ResourceManager.GetString("NazivOglasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string NazivOglasaLen {
            get {
                return ResourceManager.GetString("NazivOglasaLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti naziv oglasa.
        /// </summary>
        public static string NazivOglasaReq {
            get {
                return ResourceManager.GetString("NazivOglasaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv tipa korisnika.
        /// </summary>
        public static string NazivTipaKorisnika {
            get {
                return ResourceManager.GetString("NazivTipaKorisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string NazivTipaKorisnikaLen {
            get {
                return ResourceManager.GetString("NazivTipaKorisnikaLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti naziv tipa korisnika.
        /// </summary>
        public static string NazivTipaKorisnikaReq {
            get {
                return ResourceManager.GetString("NazivTipaKorisnikaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv tipa oglasa.
        /// </summary>
        public static string NazivTipaOglasa {
            get {
                return ResourceManager.GetString("NazivTipaOglasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string NazivTipaOglasaLen {
            get {
                return ResourceManager.GetString("NazivTipaOglasaLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti naziv tipa oglasa.
        /// </summary>
        public static string NazivTipaOglasaReq {
            get {
                return ResourceManager.GetString("NazivTipaOglasaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string Obrisi {
            get {
                return ResourceManager.GetString("Obrisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da ovo želite obrisati?.
        /// </summary>
        public static string ObrisiPitanje {
            get {
                return ResourceManager.GetString("ObrisiPitanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocjena.
        /// </summary>
        public static string Ocjena {
            get {
                return ResourceManager.GetString("Ocjena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspon ocjene.
        /// </summary>
        public static string OcjenaRange {
            get {
                return ResourceManager.GetString("OcjenaRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oglas.
        /// </summary>
        public static string Oglas {
            get {
                return ResourceManager.GetString("Oglas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oglasi.
        /// </summary>
        public static string Oglasi {
            get {
                return ResourceManager.GetString("Oglasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je odabrati oglas.
        /// </summary>
        public static string OglasReq {
            get {
                return ResourceManager.GetString("OglasReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nama.
        /// </summary>
        public static string Onama {
            get {
                return ResourceManager.GetString("Onama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis oglasa.
        /// </summary>
        public static string OpisOglasa {
            get {
                return ResourceManager.GetString("OpisOglasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 1000 znakova.
        /// </summary>
        public static string OpisOglasaLen {
            get {
                return ResourceManager.GetString("OpisOglasaLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti opis oglasa.
        /// </summary>
        public static string OpisOglasaReq {
            get {
                return ResourceManager.GetString("OpisOglasaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pita dijagram.
        /// </summary>
        public static string PitaDijagram {
            get {
                return ResourceManager.GetString("PitaDijagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše mjesto za online pregled i kupovinu starih knjiga i fakultetskih materijala.
        /// </summary>
        public static string PocetnaStranicaPoruka {
            get {
                return ResourceManager.GetString("PocetnaStranicaPoruka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poruke.
        /// </summary>
        public static string Poruke {
            get {
                return ResourceManager.GetString("Poruke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošiljaoc.
        /// </summary>
        public static string Posiljaoc {
            get {
                return ResourceManager.GetString("Posiljaoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda.
        /// </summary>
        public static string Potvrda {
            get {
                return ResourceManager.GetString("Potvrda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string Prezime {
            get {
                return ResourceManager.GetString("Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 45 znakova.
        /// </summary>
        public static string PrezimeLen {
            get {
                return ResourceManager.GetString("PrezimeLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti prezime.
        /// </summary>
        public static string PrezimeReq {
            get {
                return ResourceManager.GetString("PrezimeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primaoc.
        /// </summary>
        public static string Primaoc {
            get {
                return ResourceManager.GetString("Primaoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prvi.
        /// </summary>
        public static string Prvi {
            get {
                return ResourceManager.GetString("Prvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string Sacuvaj {
            get {
                return ResourceManager.GetString("Sacuvaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 dana.
        /// </summary>
        public static string Sedamdana {
            get {
                return ResourceManager.GetString("Sedamdana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spisak aktivnih i neaktivnih korisnika po ocjenama.
        /// </summary>
        public static string SpisakAktivnihINeaktivnihKorisnikaPoOcjenama {
            get {
                return ResourceManager.GetString("SpisakAktivnihINeaktivnihKorisnikaPoOcjenama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistike.
        /// </summary>
        public static string Statistike {
            get {
                return ResourceManager.GetString("Statistike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst komentara.
        /// </summary>
        public static string TekstKomentara {
            get {
                return ResourceManager.GetString("TekstKomentara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 1000 znakova.
        /// </summary>
        public static string TekstKomentaraLen {
            get {
                return ResourceManager.GetString("TekstKomentaraLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti komentar.
        /// </summary>
        public static string TekstKomentaraReq {
            get {
                return ResourceManager.GetString("TekstKomentaraReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst poruke.
        /// </summary>
        public static string TekstPoruke {
            get {
                return ResourceManager.GetString("TekstPoruke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina je 1000 znakova.
        /// </summary>
        public static string TekstPorukeLen {
            get {
                return ResourceManager.GetString("TekstPorukeLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti tekst poruke.
        /// </summary>
        public static string TekstPorukeReq {
            get {
                return ResourceManager.GetString("TekstPorukeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip korisnika.
        /// </summary>
        public static string TipKorisnika {
            get {
                return ResourceManager.GetString("TipKorisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je odabrati tip korisnika.
        /// </summary>
        public static string TipKorisnikaReq {
            get {
                return ResourceManager.GetString("TipKorisnikaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipa oglasa.
        /// </summary>
        public static string TipOglasa {
            get {
                return ResourceManager.GetString("TipOglasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti tipa oglasa.
        /// </summary>
        public static string TipOglasaReq {
            get {
                return ResourceManager.GetString("TipOglasaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipovi korisnika.
        /// </summary>
        public static string TipoviKorisnika {
            get {
                return ResourceManager.GetString("TipoviKorisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipovi oglasa.
        /// </summary>
        public static string TipoviOglasa {
            get {
                return ResourceManager.GetString("TipoviOglasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treci.
        /// </summary>
        public static string Treci {
            get {
                return ResourceManager.GetString("Treci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupa broj aktivnih i neaktivnih korisnika.
        /// </summary>
        public static string UkupanBrojAktivnihINeaktivnihKorisnika {
            get {
                return ResourceManager.GetString("UkupanBrojAktivnihINeaktivnihKorisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        public static string Uredi {
            get {
                return ResourceManager.GetString("Uredi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završena transakcija.
        /// </summary>
        public static string ZavrsenaTransakcija {
            get {
                return ResourceManager.GetString("ZavrsenaTransakcija", resourceCulture);
            }
        }
    }
}
